version: '3.9'

networks:
  mlops-network:
    external: true

services:
  jupyter-lab:
    restart: always
    container_name: jupyter-lab
    build: ./jupyter
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    entrypoint: >
      sh -c "
      jupyter lab 
      --ip=0.0.0.0 
      --port=8888 
      --no-browser 
      --notebook-dir=/home/jovyan/work
      --NotebookApp.token=''
      --allow-root
      "
    networks:
      mlops-network:
        ipv4_address: 172.61.0.7